### ISSUE TITLE
xplan-7

### ISSUE THREAD

**Issue by pkorduan** [srahn/kvwmap#100]
# Umstellung auf XPlanung 5.4
## ToDo's
- [ ] Erzeugung der neuen Schemata xplan_uml und xplan_gml
  - [ ] Festlegung wo die neuen Schemas hingelegt werden und wie mehrere Versionen im xplankonverter gehandhabt werden sollen.
  - Robert erstellt Liste von Packeten für die Konvertung xmi2db
  - neue Schemas werden in xplan_uml und xplan_gml
  - [ ] Erzeugen der Schema SQL-Dateien
  - [ ] Anlegen der Schema in der Datenbank
  - [ ] Inhalte die ggf. fehlen in Datenbank hinzufügen oder erzeugen
- [ ] Migration schreiben für das Anlegen der Schemata in Postgres
- [ ] Migration zur Anpassungen in den Layerdefinitionen in MySQL
- [ ] branch anlegen für Änderungen zur Berücksichtigung verschiedener Versionen
- [ ] Implementierung der Anpassungen zur Verwendung des neuen Schemas
- [ ] Tabelle mappingtable_standard_shp_to_db ergänzen
- [ ] Tabelle mappingtable_gmlas_to_gml ergänzen
- [ ] Default-Shapes schreiben für Version 5.4
- [ ] Regeln für Import der Default-Shapes anpassen
- [ ] QGIS-Formulare aus xplan_uml erzeugen für 5.4

**Comment by chseip** [comment]
So, nachdem ich einige Hürden überwinden musste, in der von mir aufgesetzten uralt Umgebung PostGIS zu installieren, klappt das nun. Ich habe xplan_gml auf NC abgelegt. Dabei musste ich im aus db2classes resultierenden SQL-Skript folgende Ersetzung vornehmen, damit ich es testweise in die DB einlesen konnte:

- `CREATE TABLE IF EXISTS` -> `CREATE TABLE IF NOT EXISTS`

Wir hatten es zwar nicht besprochen, aber ich habe im letzten Schritt auch noch db2ogr (xplan_ogr.sql) durchlaufen lassen, da es so klang, als würd in die Richtung auch noch was getan werden (liegt auch auf NC). Dazu folgendes:

- Ersetzungen:
    - `CREATE TABLE IF EXISTS` -> `CREATE TABLE IF NOT EXISTS`
    - `CREATE VIEW` -> `CREATE OR REPLACE VIEW`
    -  `:alkis_epsg` -> `25832`
- Neu:

```        
CREATE TABLE IF NOT EXISTS "aa_anlassart" (
     id         serial NOT NULL,
    value      character varying,              -- update.anlass
    PRIMARY KEY (id)
);
```

Bitte dann dazu Rückmeldungen, was für Pakete bzw. Klassen ich noch mit reinnehmen soll und natürlich, ob das alles so passt, oder ob ich noch was an den Erzeugungsskripten anpassen muss.
