### ISSUE TITLE
xplan-6

### ISSUE THREAD

**Issue by pkorduan** [srahn/kvwmap#95]
Anpassungen zur Implementierung der Planinhalte

**Comment by RKraetschmer** [comment]
### TODO

- [x] Header anpassen
- [x] Footer anpassen mit Impressum und Datenschutz
- [x] Die komplexen Attribute XP_Gemeinde und XP_ExterneReferenz werden nicht in die GML-Datei geschrieben (sie werden aber bei einer Konvertierung in die xplan_gml Datenbank geschrieben) .
- [x] Das komplexe Attribut XP_ExterneReferenz sowie die Attribute aendert und wurdegeaendertvon werden nicht in die GML-Datei geschrieben (bei XP_ExterneReferenz value und value_array_keys stimmen nicht überein: single_value 10, value_array_keys 11)
- [x] Für das Planelement Status wird beim Erstellen der GML-Datei nur der Enumerationswert (also z.B. 4000) in die GML geschrieben, nicht aber die URL des Codespace. Dies trifft ggf. für alle Codelisten zu. (die Werte werden aber bei einer Konvertierung in die xplan_gml Datenbank geschrieben).
- [ ] Für das komplexe Attribut XP_VerbundenerPlan wird die GML-ID Assoziation des Verbundenen Plans(Assoziation 'verbundenerPlan') nicht in die GML geschrieben (in xplan_gml und xplan_uml ist sie vorhanden)
- [ ] Test, ob in /demo hochgeladene Daten auch in /konverter erscheinen. Falls ja, Bugfix
- [ ] Darstellen von hochgeladenen Shapes unter Obergruppe "Hochgeladene Shapes" mit Zwischengruppen mit Planname und Untergruppe mit Shapenamen
- [ ] Upload XPlanGML Speichern von Gemeinden mit "-" Eingabe verbieten. 
- [x] Automatisierte Zuweisung des MimeTypes in XP_ExterneReferenz (bzw. XP_SpezExterneReferenz)  und automatische, nur lesbare(?), Zuordnung im Formular
- [ ] HTML-Encoding von Feldeingaben zur Behebung von ', ", < oder > Eingaben
- [ ] Stimmt Enumerationswert Beschluss in XP_ExterneReferenzTyp mit Bemerkung überein? Ansonsten Erweiterung um Bemerkung (Änderungsantrag + Datenbankerweiterung)
- [ ] Nicht alle Attribute Exportieren
- [ ] Erweiterung des Regeleditors um BP-, FP- und SO-Elemente
- [ ] Behebung von Cross-site scripting (XSS) im Regeleditor (https oder I-Frame-Problem?)
- [ ] Nur Anzeige von aktuellsten Entwurfsstände im Dienst. Hier ist zu klären, welche Daten verschiedene Entwürfe definieren (und wie vorzugehen ist, wenn diese nicht befüllt sind, da keine Pflichtfelder)
- [ ] Zuweisen von Shapes auf Plan- und Bereichsebene (BP,FP,SO) voreingestellt über ein Uploadfeld. Der Geometrieeditor soll voreingestellt ausgeschaltet sein, aber über Stelle_waehlen einschaltbar sein
- [x] Erstellung einer Mapping Tabelle von PHP mime_content_type() Rückgaben auf XP_MimeTypes
- [x] Längenbegrenzung von Feldeingaben im Formular
- [x] Test und ggf. Erweiterung von Layer-Suche
- [ ] Test und ggf. Erweiterung von Daten-Export
- [x] Filtern von Ortsteile abhängig von der ausgewählten Gemeinde 
- [x] Erstellung von Menüpunkten für BPläne, FPläne und SO-Pläne mit Unterpunkten für die jeweilige Gemeinden (für Landkreise)
- [ ] Erstellen von "Zur Landkreisstelle"-Button für Ämter-Planlisten für Landkreise
- [x] Erstellen von Fachobjekten für BP, FP und SO in einem Dienst (Gesamt-Mapfile für alle Daten, Basisdienste sollen bis dahin weiterlaufen)
- [x] Erweiterung der Wiki-Dokumentation zum xplankonverter-Plugin
- [x] Erstellen von Knopf zum und Test von Hochladen standardkonformer Shapes und automatisierter Regelerstellung
- [x] Knopf zum Erstellen von standardkonformen Shapes soll auf selber Seite bleiben, statt auf Karte zurückzuspringen (case xplankonverter_extract_standardshapes_to_regeln ) 
- [ ] Anpassung von Styles
- [x] Für Pläne von Städten und Hansestädten wird das Feld Gemeinde nicht automatisch mit der korrekten Gemeinde befüllt. Hier ist zu überprüfen, ob bezüglich des korrekten Gemeindeschlüssel-Feldes bzw. der korrekten Tabelle gefiltert wird.
- [x] Alle Gemeinden müssen ohne Komma (,) geschrieben werden. Das wurde in der gebietseinheiten und in den BP-, FP und SO-Plänen korrigiert. In FP und SO testen.
- [x] Komma aus Gemeindenamen von FP und SO-Plänen entfernen.
- [ ] Beim erstmaligen Drücken der Erstellung einer XPlanGML wird eine Fehlermeldung angezeigt (die Konvertierung läuft trotzdem durch). Sollte untersucht und falls nicht zutreffend entfernt werden
- [x] Löschen aller Testpläne
- [ ] Textwerte aus Formularfeldern von Datentypen müssen mit \" escaped werden. 
- [x] Standardnutzer für jede Stelle einrichten (Auswahlmöglichkeit default-user bitte wählen)
- [x] In SO-Plan kann es vorkommen, dass kein Anzeigename generiert werden kann, wenn das in SO optionale Feld nummer nicht befüllt wird. Für SO muss entweder der Anzeigename anders generiert werden oder Nummer auch als verpflichtendes Attribut gesetzt werden.
- [x] Attribut layer_schemaname für GMLAS auch für FP und SO einbauen
- [ ] Attributeinstellungen gemeindename und ortsteil für Suche in FP und SO überprüfen
- [ ] Mustervorlagen DXF /DWG (?)
- [ ] Filtermöglichkeit auf Planliste nach Nummer
- [ ] Filtermöglichkeiten auf Planliste nach „name“ (zusätzlich zu Anzeigename)
- [x] Testen der Abhängigkeit von istInkraftgetreten zu rechtsstand
- [x] Luftbilder in die Demoversion übernehmen
- [x] Karte soll beim Auswählen einer Geometrie im Geometrieeditor nicht neu geladen werden. Beim Neuladen werden Daten geleert
- [ ] Bereichsnummerierung kann ggf. automatisch ausgefüllt werden (bzw. Knopf zur automatischen Nummerierung einbauen)
- [ ] Falls das Feld GML-ID bei Standard-Shapes leer ist, kann eine neue GML-ID erzeugt werden (der Bereich kann nun gleichfalls leer gelassen und über die Verknüpfung im Editor befüllt werden)
- [x] Auf der Planliste soll eine Checkbox Veröffentlichung Ja/Nein eingebunden werden (ggf. gebunden an Konvertierung)
- [ ] Für XP_VerbundenerPlan soll die Auswahlliste verkleinern
- [x] Fehlermeldung beim Layer Speichern doppelt
- [x] Die Suche nach Gemeinde und Ortsteil bzw nur Gemeinde ohne Ortsteil noch einmal testen.
- [x] Veröffentlichungs Attribut in Diensten Filtern und für FP und SO-Pläne "veroeffentlicht" implementieren

**Comment by RKraetschmer** [comment]
- [ ] Die korrekte Sequenz von Attributen wird in build_gml nicht zwangsweise eingehalten, wenn eine Klasse Attribute von mehreren Type-Klassen auf gleicher Vererbungshierarchieebene erbt.
Z.B. erbt BP_BaugebietsTeilFlaeche sowohl von BP_GestaltungBaugebiet, BP_ZusaetzlicheFestsetzungen, BP_FestsetzungenBaugebiet und BP_Flaechenschlussobjekt. Die in der XSD gegebene Order wird hier in erstellten GML-Daten nicht korrekt ausgegeben.
Die derzeitige Sequenz der Element wird in in TypeInfo->fetchUmlAttributesForType() über ORDER BY festgelegt, dass über ein ...(SELECT *, row_number() OVER () AS order FROM inheritance) ... und dann über die Sequence-Order ("tv.datavalue") festgelegt wird.
Im speziellen Fall von multiplen Typen müssten aber alle -Type- Klassen (also im Beispiel BP_BaugebietsTeilFlaeche die Klassen BP_GestaltungBaugebiet, BP_ZusaetzlicheFestsetzungen und BP_FestsetzungenBaugebiet aber **nicht** BP_Flaechenschlussobjekt) auf gleicher Hierarchieebene mit derselben Ordernummer erfasst werden. Derzeit werden diese mit unterschiedlichen Order Nummern hinterlegt, die willkürlich sind.
Bei der Zusammenfassung von Type-Attributen in eine "inheritance.order" Gruppe, würde die Sequence-Nummer hier die Attribute in der korrekten Reihenfolge ausgeben

**Comment by RKraetschmer** [comment]
- [x] XPlanung-konforme Shapes werden als zip mit /var/www/data/upload/xplankonverter/id/ Folderstruktur generiert

**Comment by RKraetschmer** [comment]
Feedback von BLP nach Nutzerschulung Vorpommern-Greifswald 15.10.2019
### Bugliste:
- [x] Punktfang auf Layer B-Pläne, Flächennutzungspläne, SO-Pläne nicht möglich. Fehlermeldung im Geometrieeditor a leeres Fenster
- [ ] Geometrieeditor: Übernahme einer Flurstücksgeometrie fehlerhaft. Es werden mehrere Flurstücke ausgewählt als mit der Maus selektiert werden. Problem besteht im LK Vorpommern-Rügen (Herr Reißland) auch. Könnte ein Problem mit der Definition des WFS sein.
- [x] Geometrieeditor: Punktfang des Themas "Flurstücke" nicht möglich. Nach Einschalten der Funktion werden die vorhandenen Eckpunkte nicht zum Snappen angeboten (Rahn: Punktfang steht nur für PostGIS-Layer zur Verfügung)
- [x] Ändern der Zeichenreihenfolge der Layer: Einstellungen wurde nicht gespeichert. Beispiel siehe Stelle "Amt Torgelow-Ferdinandshof"
- [ ] Es gibt immer noch Plandokumente die nicht sichtbar sind. Z.B. der B-Plan mit dem Anzeigename "Vorhabenzeogener B-Plan nr.1, 1. Änderung Ueckermünde Stadt Plan" Gml id des Plans: 35b3ef02-baac-11e9-8ff3-4be95bcabe89) a. Ist in der Vorschau in der Sachdatenanzeige nicht sichtbar b. Dokument kann grundsätzlich nicht abgefragt werden. scheint gar nciht zu existieren, vielleicht ist der Link zum PDF nicht korrekt. (Krätschmer -> Beispielplan ist behoben, ggf. für weitere Pläne überprüfen)
- [ ] Adresssuche über Layersuche funktioniert nicht:(Rahn: Adresssuche, Flurstückssuche, 
Grundbuchblattsuche und Namensuche müssen entfernt werden, da nicht vorhanden) Layersuche im Thema Gebäude funktioniert nicht -> Ergebnis ist immer "Zu diesem Thema wurden keine Objekte gefunden!"
- [x] Suche nach Flurstück über Layersuche funktioniert nicht -> Ergebnis ist immer: "Zu diesem Thema wurden keine Objekte gefunden!"
- [ ] Redlining Zeichnung wird nicht mit in den Druck/Druckvorschau übernommen
- [ ] Redlining Pfeil wird nicht mit dargestellt beim Button "Bild Speichern" -> Bsp. siehe Stelle Amt Torgelow-Ferdinandshof
- [x] Druckrahmen soll zusätzlich zu "A4 hoch" auch "A4 Quer" und "A3 hoch+quer" verfügbar sein
- [ ] B-Plan ein hochgeladenes Dokument kann nur abgespeichert werden, wenn ein Referenzname und eine Beschreibung angegeben wird. Andernfalls kommt eine kryptische Fehlermeldung. Einfügen einer Fehlermeldung die dem Anwender verständlich macht, was das Programm erwartet, sprich das diese beiden Felder ausgefüllt werden müssen, wenn ein Dokument abgespeichert werden soll - Aktuell kann ich das Problem aber nicht mehr reproduzieren, sprich keine Beispielstelle/Beispielplan nennen bei dem das Problem auftritt.
- [x] Geometrieeditor: Wenn ein bestehender Geltungsbereich (Polygon) gelöscht werden soll, funktioniert das nicht. Bsp.: Datensatz bearbeiten -> Geometrieeditor -> vorhandene Geometrie komplett löschen (x) (um dann von vorne anzufangen eine neue zu zeichnen). Vorhandene Geometrie lässt sich nicht löschen
- [ ] Button Informationsabfrage auf angrenzende Objekte (i) funktioniert nicht. Fehler bei der Abfrage der Datenbank -> siehe Anhang der Mail
- [ ] Ein Testdatensatz aus der Schulung: Geometrie lässt sich nicht abfragen, bearbeiten oder löschen. Als Testdatensatz muss dieser aber wieder entfernt werden. Koordinate des Problemplans = 397815 5995903 (EPSG-Code 25833). Plan wird in der Liste der Bebauungspläne nicht geführt,aber in der Karte als Geltungsplan sichtbar  (Krätschmer: ->dies hängt mit einer Fehlermeldung zusammen, wenn ein Plan erstellt wird, aber für Planart nur das Auswahlfeld mit "Bitte Auswählen"  statt ein Wert geführt wird. Der fehlerhafte Plan wurde bereits gelöscht)

### Wunschliste
- [ ] Menüpunkt "letzte Suche" hinzufügen", soll das letzte ausgefüllt Suchformular noch einmal aufrufen
- [ ] Gibt es für die Landkreisadmins eine Möglichkeit einzusehen, welche Datensätze von den Amtsverwaltungen verändert wurden und wann?

**Comment by RKraetschmer** [comment]
- [x] Neue Werte für Codelisten (z.B. status in bp_plan oder planart in so_plan) werden nicht vollständig in die Datenbank geschrieben und deswegen auch nicht vollständig in die GML übertragen ( es wird nur der ID-Wert geschrieben). Ist valides GML, erlaubt aber keine Überprüfung der Codelisten durch Dritte, da nicht klar ist, auf welche Liste der Wert verweist
