### ISSUE TITLE
metro-1 Metropolplaner Offene Punkte

### ISSUE THREAD

**Issue by RKraetschmer** [srahn/kvwmap#97]
**TODO Metropolplaner**
- **Quellenvermerk nach Deutschlandlizenz 2.0**
   - [x] Dokument zum Verlinken in LayerAttributions für zusammengefasste Vektordienste
   - [x] Einzelverweise der Rasterpläne zum Verlinken in LayerAttributions
   - [x] Allgemeiner Vermerk der Metropolregion

- [x] Haftungsausschuss Text einbinden (Textvorschlag Stadt Oldenburg)

- **Metadaten**
  - [x] Einbinden weiterer Metadatenquellen aus Bremen und von Hintergrundkarten (wie kannmehr als eine CSW-Schnittstelle in rest-services konfiguriert werden?)
  - [x] Metadaten für Diepholz, Osterholz, Wesermarsch, Bremen und Bremerhaven einbinden
  - [ ] Vorschlag zum Thema "gute" Metadaten für die Verwendung im Metropolplaner erarbeiten
- [x] Legende für Wesermarsch einbinden
- [ ] Benutzbarkeit der Maßstabsumschaltung gewährleisten
- [x] Themensuche oben rechts sollte mindestens deaktiviert werden, idealerweise aber sogar korrekt funktionieren
- [x] Test AJAX-Request für alle Layer (entweder ausschalten oder Ergebnisse wiedergeben, aber keine Fehlermeldungen)
- [x] Korrekte und vollständige GetFeatureInfo-Informationen anzeigen
- [x] GetFeatureInfo-URLs mit HTML Tags versehen
- [x] GetFeatureInfo-Enumerationen und komplexe Datentypen korrekt auflösen und sprechend ausgeben (sofern möglich)
- [ ] Menüpunkte (auf Basis des Planzeichenkatalogs) sortiert nach Z-Ordnung Fläche - Linie - Punkte
- [ ] Weiterführung des FNP-Planzeichenkatalogs (ggf. in Datenbank und als HTML-Tabelle?)
- [x] Abstimmung mit GDIs und der Geschäftsstelle Metropolregion, wo Metadaten verankert werden (Ziel: Daten sollen nur einmal von der GDI-DE zu finden sein)
- [x] Überprüfen, in wieweit Gewerbeflächenkataster Bremerhaven auch über den Metropolplaner angeboten werden kann
- [x] Test zum Einbinden von externen WMS und WFS aus Niedersachsen und Bremen
- [x] Vollständige Visualisierung der Daten
- [x] Zuschnitt der Daten mit Konvertierung_id Filter testen (siehe Karte mit Stelle_id filter)
- [x] Ausgabe der komplexen GML einbinden
- [x] gliederung1, gliederung2 in FNP Vorschlag für alle Ausprägungen ausarbeiten
- [x] Einlesen externer Codelistenwerte aus Bremen in die Datenbank
- [ ] Vertikale Ordnung der FNPs: Flächenschlussobjekte, Flächenobjekte, Linienobjekte, Punkte soll falls möglich in der Menüordnung eingehalten werden
- [x] Test-Umlaufrichtung der Daten bei Visualisierung für Bremen
- [x] Test-Umlaufrichtung bei Konverterausgabe nach Einlesen aus GML (Bremen)
- [x] Entnahme nicht-verwendeter Planzeichengruppen (z.B. Maß der baul. Nutzung) aus der Menühierarchie
- [x] Schreiben multipler Externer Referenzen bei Konvertierung (aus BLP übernehmen, ggf. Software updaten)
- [x] Anzeige multipler Externer Referenzen über GetFeatureInfo bei Click auf Planfläche (inklusive weiterer relevanter Planattribute und a href Highlighting der Referenz über GFI Template)
- [x] Kompletter Zuschnitt RROP auf Landkreisgrenzen + Überprüfung
- [x] Vertex-Order für FNP Bremerhaven umdrehen (ST_Reverse), Test ob dies auch für den FNP Bremen zutrifft ( in Teilen oder vollständig?)
- [x] PNG Symbole in SVG umwandeln
- [ ] Set Extent für Stellen auf Plangrenzen
- [x] fix /model/kvwmap.php Einlesevorgang mit GMLAS $GUI->formvars['20....
- [x] Überprüfen wie für FNP Bremen Arc und Curve-Geometries ausgegeben werden (siehe auch Umlaufrichtung)
- [x] Fix Startseite Darstellung Internet Explorer
- [x] Karte aus Header nur in Home anzeigen
- [x] Für Plandokumente Karte an Startseite Metropolplaner anpassen (mit Namen der Gebietskörperschaften)
- [x] Zum Testen 1 Account pro Planträger anlegen
- [x] Einbinden der aus der Landesplanung übermittelten SVGs
- [x] Extra Darstellungsklassen für Rohstoff, Sport, Leitungstrassen etc. Untertypen nach Attribuierung
- [x] Set Reference Scale für Darstellung auf 1:10.000 oder 1:5.000 für RROP Objekte
- [x] Werkzeuge - Druck einbinden + passendes Backend (z.B. MapfishPrint 3)
- LK Osnabrück
   - [x] Die „alte“ Begrifflichkeit „Vorsorgegebiet Rohstoffgewinnung“, die unserem RROP entspricht, wird in der Layersteuerung aufgeführt, die entsprechenden Vektordaten werden aber mittels der neuen Bezeichnung „Vorbehaltsgebiet Rohstoffgewinnung“ geschaltet.
  - [x] Im Bereich „Verkehr“, „Verkehr – Schiene“ fehlt der Layer zur Beschreibung der Elektrifizierung (elektrischer Betrieb).
  - [x] Im Datenbestand „Vorranggebiet Autobahn“ wird das Attribut „rechtscharakter“ nicht korrekt, wodurch die Ausprägung „vordringlicher Bedarf“ nicht richtig dargestellt wird.
  - [x] Neue und alte Begrifflichkeiten und Definitionen von regional- und überregional bedeutsamen Hauptverkehrsstraßen sind gemischt und werden nicht eindeutig dargestellt.
- [x] SVG Darstellung Punktsymbole (Wilhelmshaven)

- **Los 2**
- [x] GeoServer aufsetzen
- [x] INSPIRE-Tabellen konfiguren
- [x] AppSchema-Datei erstellen
- [x] FNP-Mapping auf INSPIRE festlegen
- [x] XSL-T testen und SO-Elemente, BP-Elemente (aus Wilhelmshaven) und Präsentationsobjekte auch übernehmen (-> laut INSPIRE-Transformation AG Modellierung werden Präsentationsobjekte nicht nach INSPIRE übertragen, SO ist ergänzt)
- [x] XSL-T BP_Wegerecht und BP_VerEntsorgung in XSL-T übernehmen
- [x] Metadaten
- [x] Styles
- [x] Validierung
- [x] Performance-Tests
- [x] Einbinden Veröffentlichfunktion in Mapfile (für Entwurfspläne Wesermarsch und Friesland vor Liveschaltung)
- [x] PDF-Dokumente Cuxhaven einbinden (https://cuxland-gis.landkreis-cuxhaven.de/gisdata/rrop/RROP_LK-Cuxhaven_Text_Rechtskraft_Oktober2017.pdf). Wie sind diese am besten direkt aus dem Dienst auszulesen bzw. wo einbinden? Auch in GFI? oder nur über Dokumente?

**Comment by RKraetschmer** [comment]
Zur Testschaltung:
- [x] Session-Zeit für Apache Login erhöhen
- [x] Konverter vorerst aus Menü entfernen
- [x] i-Knopf nur für Metadaten anzeigen, wo dies bereits implementiert ist.
- [x] Suche anpassen an Layersuche
- [x] Buttons auf Home-Seite an Kartenanwendung, Plandokumente und Lizenz anpassen
- [x] Evaluieren, ob Fachdatenmenüpunkt als Obermenüpunkt in mehrere andere Obermenüpunkte geteilt werden kann => Nicht durch normale Konfiguration des Masterportals möglich
- [x] Nur ein Log-in für Seite
- [x] Ausloggen - Möglichkeit

**Comment by RKraetschmer** [comment]
Feedback von Bremen
**Veränderungsvorschläge**

- [x] Das Themenmenü sollte nicht verschwinden beim Verschieben des Bildes/Pan
- [x] Das Themenmenü sollte nicht verschwinden beim Schließen der vorher geöffneten Info
- Themenmenü lässt sich über Pin (neben Fragezeichen) fixieren, ist aber nicht standardmäßig aktiviert. Die Option hierzu ist in den js/json Konfigurationsdateien nicht vorhanden., d.h. es müsste Code geändert werden
- [x] Es wäre praktisch, die Legendenfenster größer aufziehen zu können (derzeit über Masterportal Einschränkung nicht möglich)

**XPlan-basierte FP-Plandarstellung - Bremen**

- [x] Fp_VerEntsorgung WK-Fläche ist gelb flächig dargestellt, sollte Punktlinie sein.
- [x] FP_GenerischesObjekt Baufl. mit Grünfunktion sollte schraffiert sein?
- [x] FP_GenerischesObjekt Prüfbereich_Wohnen-Punkt ist nicht wie im Original dargestellt
- [x] SO_Schienenverkehrsrecht-Punkt (OEPNV Umsteige- und Endpunkte) ist etwas klein
- [x] FP_SchutzPflegeEntwicklung Ausgleichsflächen-Punkte sind nicht wie im Original dargestellt
- [x] Fläche Altablagerung nur mit schwarzer Linie
- [x] SO_Schienenverkehrsrecht OEPNV schwarz
- [x] SO_Luftverkehrsrecht Punkt ist sehr groß
- [x] Unter FP_GenerischesObjekt Bauflächen Gewerbe Option liegt keine Grünfläche mehr
- Folgende Flächendarstellungen müssten über Flächenschlussobjekten liegen
   - [x] FP_ZentralerVersorgungsbereich
  - [x] FP_VerEntsorgung WK
  - [x] FP_GenerischesObjekt Zu sicherende Grünfläche auf Bauflächen
  - [x] SO_Gebiet Historische Ortskerne
- Folgende Flächen sind nicht dargestellt
  - [x] FP_GenerischesObjekt Bauflächen Wohnen/Gemischt/Option sowie Gestaltungsraum
  - [x] FP_Kennzeichnung Bergbau
- Folgende Linien sind nicht dargestellt:
  - [x] FP_GenerischesObjekt Gruenv_Sicherung / Entwickung
- Folgende Punkte sind nicht dargestellt:
  - [x] XP_PPO
  - [x] FP_VerEntsorgung WK

**Comment by RKraetschmer** [comment]
Cloppenburg
- [x] Thema 2. Natur und Landschaft
- [x] Kulturgütersymbole sind zu klein
- [x] Standorte für Erholung werden nicht angezeigt
- [x] Im Bereich Rohstoffe hatten wir einige Gebiete, die nicht genehmigt wurden, diese sind hier nicht zu erkennen.
- [x] Der Bodenarttyp der Rohstoffe wird nicht angezeigt, in der Rechtskraft Fassung geschieht dies über Symbole
- [x] Im Bereich Verkehr fehlen die Symbole für Haltestellen der Eisenbahn und die Anschlussstelleen für Autobahnen. In unserem Rechtsplan sind geplante Maßnahmen angeführt, diese sind nicht zu erkennen
- [x] Im Bereich Abfall fehlen die Symbole für Deponien

**Comment by RKraetschmer** [comment]
Osterholz
- [x] Fehlende Darstellung Landwirtschaft -> Grund: Unspezifiziert für gliederung2, da keine angabe von Grund

**Comment by RKraetschmer** [comment]
- [x] Bereitstellung Dokument Vorgabe Rasterstruktur

**Comment by RKraetschmer** [comment]
Diepholz
- [x] Die Planzeichen 10.36 – Vorranggebiet Hauptverkehrsstraße und 10.37 Vorbehaltsgebiet Hauptverkehrsstraße werden identisch dargestellt.
- [x] Die Planzeichen 3.01 Vorranggebiet ruhige Erholung in Natur und Landschaft (alte Bezeichnung) und 3.03 Vorbehaltsgebiet Erholung (alte Bezeichnung) werden identisch dargestellt.
- [x] Für den Dienst https://gis.diepholz.de/arcgis/services/WMS/WMS_Erneuerbare_Energien/MapServer/WMSServer ist zwar ein ProxyPass eingerichtet, dieser lässt sich aber nicht einbinden (die URL lässt sich jedoch aufrufen). Ggf. wegen 301 MovedPermanently status-code?

- Ist über lokale Mockup Dienstdatei behoben. Sobald der Diepholz-Dienst langfristig nach CSW-Vorgabe läuft, kann dies umgestellt werden

**Comment by RKraetschmer** [comment]
Cloppenburg

- [x] Bei den Vorranggebieten Erholung fehlen die Symbole
- [x] Vorsorgegebiete Erholung fehlen komplett
- [x] Vorranggebiete bei Rohstoffen haben keine Symbole und haben eine leicht andere Symbologie
- [x] Bei Verkehr Schiene fehlen Haltestellen
- [x] Die Planungen im Bereich Schiene sollten als Vorbehaltsgebiete auftauchen;
- [x] Hinter dem Punkt 10.25 „Park und Rade“ verbergen sich die Buslinien
- [x] Bei Verkehr Straße fehlen Anschlussstellen und Buslinien (s.o. Park and Ride), die Buslinien sollten nachrichtlich auftauchen;
- [x]  Die Planungen im Bereich Straße sollten als Vorbehaltsgebiete auftauchen;
- [x]  Außerdem haben Hauptverkehrslinien und Regionale Straßen die gleiche Symbologie
- [x]  Bei Verkehr „Wasserverkehr“ fehlen die Planungen, diese sollten als Vorbehaltsgebiete auftauchen;
- [x]   Bei der Wasserversorgung haben die Fernwasserleitungen keine Symbole
- [x]   Bei der Abfallwirtschaft haben die Vorranggebiete keine Symbole

**Comment by RKraetschmer** [comment]
Friesland:
3. Erholung
- [x] 03.01 Vorranggebiet Landschaftsbezogene Erholung : hier ist nur das Punktsymbol vorhanden, die Polygondarstellung  fehlt.
- [x] 03.02. Vorranggebiet infrastrukturbezogene Erholung: hier ist nur das Punktsymbol vorhanden, die Polygondarstellung  fehlt.
- [x] 03.08 Vorranggebiet regional bedeutsame Sportanlage: fehlt  komplett
- [x] 03.09 Vorranggebiet regional bedeutsamer Wanderweg: Hier  fehlt die Kennzeichnung  um welche Arte des Wanderweges es sich handelt  z.b. „F“ für Fahrradfahren
4. Landwirtschaft
- [x] 04.01: fehlt im Nordteil des Landkreises
- [x] 04.02: fehlt komplett
9. Rohstoffgewinnung
- [x] 09.01 Vorranggebiet Rohstoffgewinnung, 
- [x] 09.02. Vorranggebiet  Rohstoffsicherung
- [x]  09.03. Vorbehaltsgebiet Rohstoffgewinnung
- [x] Die Planzeichen von 09.02 und 09.03 sind vertauscht. 09.03. hat lt. Planzeichenkatalog keine Punktstruktur, 09.02 hat eine Punktstruktur. Für alle 3 Themen: Die angegebenen Bezeichnungen der Rohstofftypen sind falsch. Hier wird immer „Ki“ angegeben. Es müsste aber eine Unterscheidung zwischen  „S“, „To“ und  „Kl“  geben.
10. Verkehr-Schiene
- [x] 10.07: der Buchstabe „I“ im Kreis an der Stecke fehlt.
- [x] 10.15: Vorranggebiet Bahnstation fehlt
- [x]  10.20: Vorranggebiet Elektrische Betrieb fehlt
10. Verkehr-Wasserstraße
- [x] 10.54 Vorranggebiet Seehafen/Binnenhafen: Jade-Weser Port (Whv)  wird nicht dargestellt (Krätschmer -> Liegt innerhalb des Gebiets des FNP Wilhelmshaven und würde diesen somit überschneiden, deswegen Darstellung nicht möglich)
11. Wasserwirtschaft
- [x] 11.08: Vorranggebiet Fernwasserleitung: Es fehlt das „W“ an der Leitung
- [x] 11.22 Vorranggebiet HauptabwasserleitungEs fehlt das „W“ bzw. „S“ an der Leitung
- [x] 11.32 Vorranggebiet Deich: Darstellung ist nur eine Linie, lt. Planzeichenkatalog anders
13. Energie
- [x] 13.08. ist in der Themenübersicht doppelt vorhanden ( Vorranggebiet ELT-Leitungstrasse  und Vorranggebiet Leitungstrasse): Unsere Leitungen sollten in  „13.08: Vorranggebiet ELT-Leitungstrasse“ sein. Sie sind aber in dem anderen Thema dargestellt.
- [x] Es fehlt außerdem die Leistungsangabe im (freigestellten)Rechteck
- [x] 13.14: Vorranggebiet Verstetigung und Speicherung von regenerativer Energie fehlt in Themenübersicht und Karte , muss ergänzt werden.
- [x] 13.16: Vorranggebiet Rohrfernleitung
- [x] Die Kennzeichnung der  Art des Transportgutes  fehlt, muss durch Buchtstaben im Kreis gekennzeichnet werden. („Eö“, „G“; „P“)
15. Nachrichtliche Darstellungen:
- [x] 15.06 Gewässer fehlt
- [x] 15.12 Grenze Planungsraum fehlt

**Comment by RKraetschmer** [comment]
LK Osnabrück
- [x] Die Darstellung des Ordnungsraumes fehlt. In den xPlan Daten gibt es hierzu einzelne Features im Bereich „RP Raumkategorie Polygon“
- [x] Die Darstellung der solitären Einzelhandelsstandorte fehlt. In den xPlan Daten ist das die Featureklasse „RP Einzelhandel Polygon“
- [x] Die Darstellung der Vorsorgegebiete für Erholung fehlt. Sie werden weder unter dem Thema „03.03 Vorbehaltsgebiet Erholung (alte Bezeichnung)“ noch unter „03.03 Vorbehaltsgebiet landschaftsbezogene Erholung“ dargestellt. In den xPlan Daten gibt es die entsprechenden Features in der Klasse „RP Erholung Polygon“ mit dem Attribut „TYPERHOLUNG“ „1000“
- [x] Die Darstellung für Bahnhöfe mit ÖPNV Funktion fehlt. In den xPlan Daten ist das die Featureklasse „RP Schienenverkehr Point“. Die Elektrifizierung an den Eisenbahnstrecken wird nicht dargestellt
- [x] In der xPlan Featureklasse „RP Schienenverkehr Polyline“ ist es das Attribut „BESONDERERTYP“
- [x] Die Darstellung zu Anlagen mit großem Flächenbedarf fehlt
- [x] Alle Vorranggebiete und Vorsorgegebiete für Rohstoffgewinnung sind mit dem Rohstoffsymbol „Ki“ für Kies dargestellt
- [x] Das Attribut „text“ der xPlan Featureklasse „RP Rohstoff Polygon“ wurde nicht korrekt berücksichtigt
- [x] Beim Schienenverkehr wird keine Unterscheidung nach Haupt- und sonstiger Eisenbahnstrecke vorgenommen

**Comment by RKraetschmer** [comment]
- [x] Einlesen neueste GML Wilhelmshaven

**Comment by RKraetschmer** [comment]
INSPIRE-Transformation FNP Bremen

- [x] fehlerhafter SupplementaryRegulation Link für AirportAcitvities (_1_0 statt _10)
- [x] http://dcodelist.gdi-de.org/register/codelist/5_7_1_1_DB_Bahnanlage fehlt (-> Ist nach Liste der AG Modellierung hinterlegt. In der Online-Version des Katalogs wird hier stattdessen 5_7_1_1_DB-Bahnanlage mit Bindestrich statt Unterstricht verwendet. Ist nun ausgetauscht (Auch fuer OEPNV-Haltestelle) Hier sollte am besten im Mapping und in der Codeliste der Bindestrich entnommen werden))

- [x] In unserem FP gibt es einen Punkt für Dauerkleingarten, unter dem keine entsprechende Fläche liegt. Bei den ZoningElements und den SupplementaryRegulation Points werden sie unterschiedlich transformiert: Dauerkleingarten  in ZoningElements :                                1_1_3_AgriculturalProductionForOwnConsumption,           Name: landwirtschaftliche Erzeugung für den Eigenverbrauch Dauerkleingarten  in SupplementaryRegulation Point:        7_2_3_Recreation,                                                              Name: recreation Da wäre meine Frage, ob das wirklich so gewollt ist?
Ist so implementiert da Fläche Flächenschluss besitzt (und deswegen ZoningElement ist) und Punkt keinen Flächenschluss besitzen darf, deswegen SupplementaryRegulation (mit unterschiedlichen Codelisten: HILUCS respektive HSRCL).

**Comment by RKraetschmer** [comment]
Workshop III Metropolplaner Protokoll TODO

- [x] RROP Flächenelemente mit 80% Opacity darstellen, wenn diese nur mit einer Farbe gefüllt sind
- [x] Entwurfsvorschlag von GDI-Service und regio-gmbh, wie Dokumente in der Seite eingebunden werden können
- [x] Untersuchen, ob Vorbehalts- und Vorsorgegebiete in einem Untermenüpunkt zusammengefasst werden können
- [x] Falls möglich Pin im Layerbaum  standardmäßig einschalten
- [x] Dienst für Gemeindegrenzen bzw. Landkreisgrenzen aus externem WMS einbinden (in einem eigenen Menüpunkt "Sonstiges"
- [x] Erstellung von Transformationsdatei von Flächennutzungsplänen in XPlanung nach INSPIRE
- [x] Korrekte Darstellung Landwirtschaft im LK Osterholz
- [x] PDF mit Quellenangaben nach Deutschlandlizenz
- [x] Umbennennung Haftungsausschluss in Salvatorische Klausel (?) (abgelehnt)
- [x] FNP GML über Landing Page zum Download anbieten
- [x] Vorschläge für Attribute gliederung1  und gliederung2 für FNP
- [x] Download von GML über Info-Fenster überprüfen
- [x] Enumerationen innerhalb von GetFeatureInfos als sprechender Text wiedergeben
- [x] Möglichkeit zur Option eines rechteckigen Zoomfensters evaluieren

**Comment by RKraetschmer** [comment]
Friesland
- [x] Konvertierung neuer Entwurfsstand (Shapes)
- [x] Zuschnitt neue Shapes
